pub mod archarm;
pub mod archlinux;
pub mod archlinuxcn;
pub mod artix;
pub mod cachyos;
pub mod chaotic;
// pub mod debian;
pub mod endeavouros;
pub mod manjaro;
pub mod rebornos;
pub mod stdin;
// pub mod ubuntu;
